package consts

const (
	MYSQL_USER     = "MYSQL_USER"
	MYSQL_PASSWORD = "MYSQL_PASSWORD"
	MYSQL_HOST     = "MYSQL_HOST"
	EMAIL_FROM     = "EMAIL_FROM"
	EMAIL_HOST     = "EMAIL_HOST"
	EMAIL_PASSWORD = "EMAIL_PASSWORD"
	JWT_SECRET     = "JWT_SECRET"
)
